Repository nank1ro/solidart, pull requests merged in 2023-06, with the labels that each got.

#24 [feat] show signal fn
  docs/flutter/show.mdx
  docs/learning/resources.mdx
  examples/counter/lib/main.dart
  packages/flutter_solidart/CHANGELOG.md
  packages/flutter_solidart/example/lib/pages/show.dart
  packages/flutter_solidart/example/lib/pages/solid.dart
  packages/flutter_solidart/lib/src/widgets/show.dart
  packages/flutter_solidart/lib/src/widgets/signal_builder.dart
  packages/flutter_solidart/pubspec.yaml
  packages/flutter_solidart/test/flutter_solidart_test.dart
  packages/solidart/test/solidart_test.dart
  packages/solidart_lint/CHANGELOG.md
  packages/solidart_lint/lib/src/assists/wrap_with_resource_builder.dart
  packages/solidart_lint/pubspec.yaml
Labels: enhancement

#30 Chore/add contributors
  .all-contributorsrc
  README.md
Labels: chore

#36 [feat] hasPreviousValue getter
  packages/solidart/lib/src/core/read_signal.dart
  packages/solidart/lib/src/core/signal.dart
Labels: feature

#34 [feat] support refreshing in error state
  README.md
  docs/flutter/resource-builder.mdx
  packages/flutter_solidart/README.md
  packages/flutter_solidart/example/lib/pages/resource.dart
  packages/flutter_solidart/lib/src/widgets/resource_builder.dart
  packages/flutter_solidart/test/flutter_solidart_test.dart
  packages/solidart/lib/src/core/resource.dart
  packages/solidart/test/solidart_test.dart
Labels: feature

#38 [chore] Rename `resource` param to `state`
  packages/flutter_solidart/lib/src/widgets/resource_builder.dart
Labels: chore

#40 [chore] improve signal has previous value
  README.md
  docs/flutter/resource-builder.mdx
  examples/counter/pubspec.yaml
  examples/todos/pubspec.yaml
  examples/toggle_theme/pubspec.yaml
  packages/flutter_solidart/CHANGELOG.md
  packages/flutter_solidart/README.md
  packages/flutter_solidart/example/lib/pages/resource.dart
  packages/flutter_solidart/example/pubspec.yaml
  packages/flutter_solidart/pubspec.yaml
  packages/solidart/CHANGELOG.md
  packages/solidart/lib/src/core/computed.dart
  packages/solidart/lib/src/core/read_signal.dart
  packages/solidart/lib/src/core/resource.dart
  packages/solidart/lib/src/core/signal.dart
  packages/solidart/lib/src/core/signal_base.dart
  packages/solidart/pubspec.yaml
  packages/solidart/test/solidart_test.dart
  packages/solidart_lint/example/pubspec.yaml
Labels: chore

#41 [chore] add melos and very good cli
  .github/workflows/build.yml
  examples/counter/lib/main.dart
  melos.yaml
  packages/flutter_solidart/example/test/widget_test.dart
  pubspec.yaml
  scripts/combine_coverage.sh
  scripts/coverage.sh
Labels: chore

#46 fix/solidart_lint resource builder remove refreshing
  melos.yaml
  packages/solidart_lint/CHANGELOG.md
  packages/solidart_lint/lib/src/assists/wrap_with_resource_builder.dart
  packages/solidart_lint/pubspec.yaml
Labels: bug
